### ISSUE TITLE
[ReactInVue] Warning: Received `true` for a non-boolean attribute `ref_for`.

### ISSUE THREAD

**Issue by baijunjie** [gloriasoft/veaury#124]
今天重新安装了项目依赖，并且更新了 react-dom 依赖到@18.3，发现又出现了新的警告：

<img width="566" alt="image" src="https://github.com/devilwjp/veaury/assets/7956480/12d9e817-9a93-47b9-8221-9e5a8bc85831">

我检索了一下依赖库的代码，发现 `ref_for` 是在 `@vue` 中定义的，然后在 react-dom 中引发的警告，看上去这个问题和之前遇到的类似。https://github.com/devilwjp/veaury/issues/115

目前来看，也仅仅是个警告，并没有其他副作用。就是比较影响 debug

我想之后随着 react 更新，可能还会出现其他的警告，不知道是否有方法能够彻底解决类似的问题？或者通过一些配置手段能够让开发者灵活解决这个问题？

**Comment by devilwjp** [comment]
@baijunjie 这个问题和之前的不同，我想是可以避免的，应该是哪里还没有杜绝掉无用的属性传递

**Comment by devilwjp** [comment]
@baijunjie 最好能提供我一个例子

**Comment by baijunjie** [comment]
> @baijunjie 最好能提供我一个例子


很奇怪，我无法使用在线的工具重现这个问题。
我在本地制作了一个 demo，上传到了我的GitHub，你可以下载下来查看：
https://github.com/baijunjie/veaury-issue-demo
这个demo包含了两个问题：
第一个问题就是这个警告的问题
<img width="1251" alt="image" src="https://github.com/devilwjp/veaury/assets/7956480/88c9207a-96d2-48ab-939b-e6da63dc6034">
第二个问题与这个警告无关，稍后我会重新开一个issue，辛苦了🙏🏻

**Comment by devilwjp** [comment]
@baijunjie 这个不是veaury的问题，是因为Link组件对于ref_for的值期望字符串的类型，而当缺省ref_for时，则默认判断为布尔值了，可以手动指明ref_for参数为一个空字符串，如下图所示
![image](https://github.com/user-attachments/assets/cad96e62-34cb-499f-8484-4e97f6b17a5c)

**Comment by devilwjp** [comment]
@baijunjie 已修复，更新到2.5.1
