### ISSUE TITLE
【ReactInVue】TypeError: Cannot read properties of undefined (reading 'apply')

### ISSUE THREAD

**Issue by citynook** [gloriasoft/veaury#126]
在 vue3 项目中使用了 amis editor 组件，在窗口关闭时报错：TypeError: Cannot read properties of undefined (reading 'apply')

我不清楚是 veaury 的问题还是 amis editor 的问题，所以分别提交了 issue，希望有空的时候看一下是什么原因造成的。

demo仓库：https://github.com/citynook/amiseditor-vue
问题复现步骤:
1. 执行 npm install --legacy-peer-deps 安装依赖
2. 执行npm run dev启动项目，用谷歌浏览器进入主页面，按F12打开开发工具
3. 点击【Open Editor】按钮弹出 Amis 编辑对话框
4. 关闭对话框，此时控制台会输出错误信息

![image](https://github.com/devilwjp/veaury/assets/127393297/d921c372-1ac4-458b-9e42-0a53ceb8831c)

**Comment by devilwjp** [comment]
@citynook 这个issue我看和你提在amis的issue很像，那个issue已经被amis解决了
https://github.com/baidu/amis/issues/8350

**Comment by citynook** [comment]
@devilwjp 抱歉，最近几天有事没上线，今天才有时间回复。

我本地开发环境：
开发工具：visual studio code
node: 18.16.1
npm: 9.5.1

删除本地node_modules 目录并执行  npm install --legacy-peer-deps 可以正常安装依赖。
若安装依赖还有问题，烦请稍个图片上来，不过我对前端使用时间并不长，可能无法提供解决方案，但多看看总是没错的。

**Comment by citynook** [comment]
@devilwjp 请问还是无法安装依赖吗？

**Comment by citynook** [comment]
@devilwjp 抱歉，忘记替换公司内部的仓库，请将 .npmrc 的内容换成下面的，再重装下依赖就可以了。
```
shamefully-hoist=true
strict-peer-dependencies=false
registry=https://registry.npmmirror.com/
```

另外， 在amis提交的issue #10268，昨天工程师回复如下，希望能提供帮助：
![image](https://github.com/gloriasoft/veaury/assets/127393297/1a29148a-0516-4477-995e-9906bc0849fb)

**Comment by devilwjp** [comment]
@citynook 升级到2.4.1

**Comment by citynook** [comment]
升级新版本后此问题解决，大佬V5

**Comment by enkialtria** [comment]
请问一下是把什么升级到新版本？
这是我的包
"amis": "^6.0.0",
"amis-core": "^6.0.0",
"amis-editor": "^6.0.0",
"amis-editor-core": "^6.0.0",
 "veaury": "^2.3.12",

**Comment by devilwjp** [comment]
@enkialtria veaury
