### ISSUE TITLE
我的构建工具是rollup应该怎么配置呀，支持rollup吗？

### ISSUE THREAD

**Issue by gansong99** [gloriasoft/veaury#130]

**Comment by devilwjp** [comment]
@gansong99 你可以尝试使用veaury的vite插件在rollup上试试，如果不行的话，提供一个测试项目地址给我，然后考虑提供一个rollup插件

**Comment by gansong99** [comment]
@devilwjp 谢谢大佬，配置的问题已经解决了，不过又遇到一个问题，我用的是react项目引用vue2的第三方包，使用[vuereact-combined]，遇到一个mixins的报错信息，是因为vuereact-combined不支持mixins导致的吗？vue组件里写了mixins，以下是我的报错信息：
![WechatIMG980](https://github.com/gloriasoft/veaury/assets/54786769/e6dda0fd-a368-4b74-a09f-afac93f12877)
![WechatIMG979](https://github.com/gloriasoft/veaury/assets/54786769/a5701fc1-8053-4ba4-b2e9-be767b567f36)

**Comment by devilwjp** [comment]
@gansong99 `vuereact-combined`的问题不要在`veaury`提
