### ISSUE TITLE
vue3+vite+ts项目引入react组件

### ISSUE THREAD

**Issue by Ljy66** [gloriasoft/veaury#131]
主项目是vue3，使用applyReactInVue引入react组件后会报以下错误，本地运行时效果正常，打包的时候ts编译过不了
![image](https://github.com/gloriasoft/veaury/assets/32189692/4b23c02e-f30d-42b5-abf0-b3baecad73e5)

**Comment by Gijela** [comment]
有示例吗

**Comment by devilwjp** [comment]
@Ljy66 vue和react的ts声明会出现冲突，需要自行进行处理，文档里有相关的说明，给出了一个处理ts冲突的例子，但是实际情况还是要根据你vue和react的版本进行自行处理

https://github.com/gloriasoft/veaury?tab=readme-ov-file#typescript-jsx-types-conflict-caused-by-vue-and-react-at-the-same-time

**Comment by Ljy66** [comment]
@devilwjp 好的，谢谢回复
