### ISSUE TITLE
不能用于生成环境吗

### ISSUE THREAD

**Issue by Gijela** [gloriasoft/veaury#132]
如题，只能在开发环境使用，不能在生成环境使用？
![image](https://github.com/gloriasoft/veaury/assets/82071209/3e4f8765-1991-436a-b14a-a0a10bbb4238)

**Comment by devilwjp** [comment]
@Gijela 这个项目是veaury的调试项目，你可以参考里面的配置用到你的自己项目的生产环境中，不推荐直接使用这个项目作为生产环境

**Comment by Gijela** [comment]
> @Gijela 这个项目是veaury的调试项目，你可以参考里面的配置用到你的自己项目的生产环境中，不推荐直接使用这个项目作为生产环境

抱歉，我理解错了。我理解为veaury不支持在生产环境中使用，因为我看到babel.config.js中的test函数且写着for dev only。
<img width="927" alt="image" src="https://github.com/gloriasoft/veaury/assets/82071209/885888be-e832-4065-b549-ffab68a80b2f">

**Comment by devilwjp** [comment]
@Gijela test函数是自定义设置触发条件的函数
