### ISSUE TITLE
vite+vue3+ts作为基础，加入reaact,  react的tsx组件报错且无法正常渲染改为jsx可以正常展示，请问是有啥东西少配置了吗

### ISSUE THREAD

**Issue by PengGangGui** [gloriasoft/veaury#134]
"react": "^18.3.1",     "react-dom": "^18.3.1",     "veaury": "^2.4.1",     "vue": "^3.4.29",
![微信截图_20240709170640](https://github.com/gloriasoft/veaury/assets/44397643/779578a4-094a-4964-8c70-ef42588a0293)
![微信截图_20240709170523](https://github.com/gloriasoft/veaury/assets/44397643/01e38c7d-71f2-4967-ad06-9bd5064e973b)
![微信截图_20240709170538](https://github.com/gloriasoft/veaury/assets/44397643/e8ad76ef-d775-4978-be4e-fe2df56499c8)
![微信截图_20240709170615](https://github.com/gloriasoft/veaury/assets/44397643/af6e3ba7-3522-4710-a5ad-c80e0b18b214)

**Comment by devilwjp** [comment]
@PengGangGui 
这个问题的根因是因为vue3+vite+ts项目中的tsconfig.json中引用了vue的一些特殊配置，将jsxImportSource的值改成了vue，导致vite中的react插件的jsxImportSource的值也被修改。

快速解决方案是对vite.config.ts中的veaury插件多加一个配置，如下：
```ts
plugins: [
    veauryVitePlugins({
      type: 'vue',
      reactOptions: {
        jsxImportSource: 'react'
      },
    })
  ],
```

长期解决方案是veaury会弥补这个问题，预期再2.4.2版本修复

**Comment by devilwjp** [comment]
@PengGangGui 2.4.2已发布

**Comment by PengGangGui** [comment]
感谢
