### ISSUE TITLE
[Vue warn]: setup() return property "__veauryInjectedProps__" should not start with "$" or "_"

### ISSUE THREAD

**Issue by ErHu1993** [gloriasoft/veaury#137]
Vue3: v3.4.35，
<script setup lang="ts"> 中使用 applyReactInVue 报警告

runtime-core.esm-bundler.js:51 [Vue warn]: setup() return property "__veauryInjectedProps__" should not start with "$" or "_" which are reserved prefixes for Vue internals.

**Comment by devilwjp** [comment]
@ErHu1993 这是veaury内部属性的命名规则，忽略这个警告

**Comment by ErHu1993** [comment]
感谢解答
