### ISSUE TITLE
自定义的事件可以触发么？

### ISSUE THREAD

**Issue by jokerleon** [gloriasoft/veaury#149]
![image](https://github.com/user-attachments/assets/4385e8fd-da5a-4c98-af91-bac0036134bd)
组件中有这样一个方法 我这样写好像无法触发 是需要我手动怎么添加这个方法么？

**Comment by devilwjp** [comment]
@jokerleon  可以触发的，等同于React组件接收的props.onGetActionRender

**Comment by jokerleon** [comment]
> @jokerleon 可以触发的，等同于React组件接收的props.onGetActionRender

这个组件不是我写的，是找的开源的组件npm安装的，里面提供的方法是getActionRender，没有on，是不是我得改下他组件里的方法名称？

**Comment by devilwjp** [comment]
@jokerleon 那就别用`@`，直接使用getActionRender属性即可

**Comment by jokerleon** [comment]
> @jokerleon 那就别用`@`，直接使用getActionRender属性即可

好

**Comment by jokerleon** [comment]
> @jokerleon 那就别用`@`，直接使用getActionRender属性即可

请教下这个问题怎么处理~感谢~
https://github.com/gloriasoft/veaury/issues/150#issue-2655519997
