### ISSUE TITLE
请教一下getReactNode的用法

### ISSUE THREAD

**Issue by jokerleon** [gloriasoft/veaury#150]
![image](https://github.com/user-attachments/assets/30526e71-f843-4f9f-8078-2d5ea22aae97)
我需要用到这个方法，我看这里写的直接写进去结构，但是我直接写会报错，把结构写成字符串又不是结构只是字符串了
![image](https://github.com/user-attachments/assets/5899ce8e-be3e-436f-a81d-d2777dbc12ad)
我这里需要把渲染好的结构用这个方法转换成reactNode，我直接写innerHTML，效果就是和字符串一样，把字符串传进去了，如果不写innerHTML，传过去的就是个空数组
![image](https://github.com/user-attachments/assets/6c599bfa-5edc-46a9-883d-8a80c241f806)
效果就是上图，我希望把这个结构转换为reactNode传进去，我应该怎么处理？

**Comment by devilwjp** [comment]
@jokerleon getReactNode方法接收的参数是VNode，而不是一个html结构

**Comment by jokerleon** [comment]
> @jokerleon getReactNode方法接收的参数是VNode，而不是一个字符串形式的html结构 首先你的Vue项目要能支持Vue的JSX，比如在script标签配置jsx，`<script setup lang="jsx">`，然后就可以在vue文件里写jsx了

好嘞 感谢 可以啦~
