### ISSUE TITLE
通过ref获取react实际实例的问题,没有找到字段__veauryReactRef__

### ISSUE THREAD

**Issue by jokerleon** [gloriasoft/veaury#152]
![image](https://github.com/user-attachments/assets/b5747c17-3c1b-4cd7-a97b-2a876784d86e)
您好，我这里需要获取react组件的实例并调用其中的方法，我看到文档这里有一个__veauryReactRef__
但是我获取这个ref打印的时候发现没有找到这个字段
![image](https://github.com/user-attachments/assets/3f7387f8-242b-47f1-a53d-133dcd757315)
![image](https://github.com/user-attachments/assets/9f40a08b-0563-4bbf-89d3-2701ed83384b)
![image](https://github.com/user-attachments/assets/bebeecf4-f9d0-4831-8fa0-497be74dcf51)
我使用的是pure模式，
这个组件内有一个current的值，在react中可以获取到然后调用方法监听事件，
![image](https://github.com/user-attachments/assets/cad6dc37-17bf-4132-9eb8-43502c0d17f5)
如果我直接获取ref后，current是undefined
![image](https://github.com/user-attachments/assets/5b1510f2-9c8d-40fa-b31a-8db153e92f76)
我想获取它的实例并调用current里面的方法，请问应该如何处理？

**Comment by devilwjp** [comment]
@jokerleon 你试一下在下一次宏任务再获取
```js
mounted() {
    setTimeout(()=>console.log(this.$refs.timelineEditorRef.__veauryReactRef__))
}
```

**Comment by jokerleon** [comment]
> ```js
> setTimeout(()=>console.log(this.$refs.timelineEditorRef.__veauryReactRef__))
> ```

获取到啦 感谢感谢~
