### ISSUE TITLE
nuxt3+vue3+react18+veaury 2.5.1，修改 nuxt 默认 srcDir 后，react 组件无法渲染

### ISSUE THREAD

**Issue by JerrySLau** [gloriasoft/veaury#153]
nuxt3+vue3+react18+veaury 2.5.1，修改 nuxt 默认 srcDir 后，react 组件无法渲染

"dependencies": {
"@vitejs/plugin-react": "^4.3.1",
"nuxt": "^3.13.0",
"react": "^18.3.1",
"react-dom": "^18.3.1",
"veaury": "^2.5.1",
"vue": "^3.5.13",
"vue-router": "^4.4.5"
},

export default defineNuxtConfig({
	alias: {
		'#ex-react': "~~/react_app",
	},
	srcDir: 'src/',
  devtools: { enabled: true },
  vite: {
    plugins: [
      // @ts-ignore
      veauryVitePlugins({
        type: 'vue',
        isNuxt: true,
      })
    ],
  },
});

**Comment by devilwjp** [comment]
@JerrySLau 提供一个完整的可以复现问题的项目

**Comment by JerrySLau** [comment]
@devilwjp 我重新 init 了一个项目，修改 src 目录后，可以了，不知之前是哪一步的问题。我自己排查一下。

多谢
