### ISSUE TITLE
vue3引用react19渲染失败

### ISSUE THREAD

**Issue by hty112** [gloriasoft/veaury#155]
本来好好的做到一半突然显示渲染失败，退回到最开始发现第一步就失败了，最基本的vue引入react组件，babel这些都没动还是文档里的样子
![image](https://github.com/user-attachments/assets/514a12b0-5269-48d8-8193-aae90544d0cf)
![image](https://github.com/user-attachments/assets/d344010c-d4d1-45fd-a2bd-7324b60802f0)
![image](https://github.com/user-attachments/assets/293af863-bb54-4850-a81b-8d4a8f9133ec)

**Comment by devilwjp** [comment]
@hty112 你这个错误和react19没关系，这个错误是你传了一个Vnode作为了reactNode，应该是JSX解析方面的问题
PS： 建议你把setVeauryOptions这步放在main.js中，因为只需要一次

**Comment by hty112** [comment]
> @hty112 你这个错误和react19没关系，这个错误是你传了一个Vnode作为了reactNode，应该是JSX解析方面的问题 PS： 建议你把setVeauryOptions这步放在main.js中，因为只需要一次

是的我想说详细点，请问这个jsx解析是怎么个解决方法，babel要改是吗

**Comment by devilwjp** [comment]
@hty112 你的vue项目是什么项目？webpack还是vite?

**Comment by hty112** [comment]
> @hty112 你的vue项目是什么项目？webpack还是vite?

webpack 
![image](https://github.com/user-attachments/assets/7d0764bf-d5d1-4aeb-b6a7-6b2c5af940d4)

**Comment by hty112** [comment]
> @hty112 你如果使用的是veaury的babel插件，那么react默认是应该放在react_app目录里的，只有react_app目录的jsx文件才会以react的方式去解析

好的谢谢
