### ISSUE TITLE
react中如何使用vue3的element plus 库

### ISSUE THREAD

**Issue by panalanjun** [gloriasoft/veaury#156]
可以出一个react中如何引入一些vue的三方库的教程吗？譬如在react项目中如何使用vue3的element plus 库，具体引入的步骤应该怎么操作？

**Comment by devilwjp** [comment]
@panalanjun 参照说明文档使用即可

**Comment by panalanjun** [comment]
> @panalanjun 参照说明文档使用即可

目前个人使用过程中，只能在每个vue组件中引入使用，譬如：

在入口js文件引入样式文件：import 'element-plus/dist/index.css'
在每个vue组件单独引用：
<template>
  <div>
    <h2>这个是Vue3 element-plus 示例组件</h2>
    <el-tabs v-model="activeName" class="demo-tabs">
      <el-tab-pane label="User" name="first">User</el-tab-pane>
      <el-tab-pane label="Config" name="second">Config</el-tab-pane>
      <el-tab-pane label="Role" name="third">Role</el-tab-pane>
      <el-tab-pane label="Task" name="fourth">Task</el-tab-pane>
    </el-tabs>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { ElTabs, ElTabPane } from 'element-plus'

const activeName = ref('first')
</script>

<style>
.demo-tabs > .el-tabs__content {
  padding: 32px;
  color: #6b778c;
  font-size: 32px;
  font-weight: 600;
}
</style>


有没有办法可以在根入口全量引入使用呢？

**Comment by panalanjun** [comment]
目前个人使用过程中，只能在每个vue组件中引入使用，譬如：

在入口js文件引入样式文件：import 'element-plus/dist/index.css'
在每个vue组件单独引用：
<template>
  <div>
    <h2>这个是Vue3 element-plus 示例组件</h2>
    <el-tabs v-model="activeName" class="demo-tabs">
      <el-tab-pane label="User" name="first">User</el-tab-pane>
      <el-tab-pane label="Config" name="second">Config</el-tab-pane>
      <el-tab-pane label="Role" name="third">Role</el-tab-pane>
      <el-tab-pane label="Task" name="fourth">Task</el-tab-pane>
    </el-tabs>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { ElTabs, ElTabPane } from 'element-plus'

const activeName = ref('first')
</script>

<style>
.demo-tabs > .el-tabs__content {
  padding: 32px;
  color: #6b778c;
  font-size: 32px;
  font-weight: 600;
}
</style>


有没有办法可以在根入口全量引入使用呢？

**Comment by panalanjun** [comment]
目前个人使用过程中，只能在每个vue组件中引入使用，譬如：

在入口js文件引入样式文件：import 'element-plus/dist/index.css'
在每个vue组件单独引用：
```
<template>
  <div>
    <h2>这个是Vue3 element-plus 示例组件</h2>
    <el-tabs v-model="activeName" class="demo-tabs">
      <el-tab-pane label="User" name="first">User</el-tab-pane>
      <el-tab-pane label="Config" name="second">Config</el-tab-pane>
      <el-tab-pane label="Role" name="third">Role</el-tab-pane>
      <el-tab-pane label="Task" name="fourth">Task</el-tab-pane>
    </el-tabs>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { ElTabs, ElTabPane } from 'element-plus'

const activeName = ref('first')
</script>

<style>
.demo-tabs > .el-tabs__content {
  padding: 32px;
  color: #6b778c;
  font-size: 32px;
  font-weight: 600;
}
</style>
```

有没有办法可以在根入口全量引入使用呢？

**Comment by panalanjun** [comment]
@devilwjp 是在你的基础项目进行调试的。

![微信图片_20241213165226](https://github.com/user-attachments/assets/a3f00d3d-83d1-4980-a13b-8e45c60f4247)


TestElementPlus.vue文件的代码如下：
```
<template>
  <div>
    <h2>这个是Vue3 element-plus 示例组件</h2>
    <el-tabs v-model="activeName" class="demo-tabs">
      <el-tab-pane label="User" name="first">User</el-tab-pane>
      <el-tab-pane label="Config" name="second">Config</el-tab-pane>
      <el-tab-pane label="Role" name="third">Role</el-tab-pane>
      <el-tab-pane label="Task" name="fourth">Task</el-tab-pane>
    </el-tabs>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import 'element-plus/dist/index.css'
import { ElTabs, ElTabPane } from 'element-plus'

const activeName = ref('first')
</script>

<style>
.demo-tabs > .el-tabs__content {
  padding: 32px;
  color: #6b778c;
  font-size: 32px;
  font-weight: 600;
}
</style>

```


效果是可以呈现的，诉求是能不能在全局入口文件全量引入：import ElementPlus from 'element-plus'，在vue技术栈中不习惯每个组件都进行 import 一次element-plus特定的组件

**Comment by devilwjp** [comment]
@panalanjun React没有全局组件得概念
