### ISSUE TITLE
React components in Nuxt 

### ISSUE THREAD

**Issue by sndrgb** [gloriasoft/veaury#2]
Hello, any experience to integrate react components in nuxt?
I'll try a bit but I always had some errors.

**Comment by devilwjp** [comment]
Is there any error message? @sndrgb

**Comment by anaibol** [comment]
It fails to parse the pages

<img width="568" alt="Screenshot 2023-07-31 at 16 13 06" src="https://github.com/devilwjp/veaury/assets/3210177/2f2a9f41-2c7f-4249-b660-3003e8645833">
<img width="612" alt="Screenshot 2023-07-31 at 16 13 29" src="https://github.com/devilwjp/veaury/assets/3210177/8d18bb40-e10f-43b4-926a-3751db2e15ab">

**Comment by devilwjp** [comment]
@sndrgb @anaibol @ekkaiasmith 
Try veaury@^2.5
https://github.com/gloriasoft/veaury?tab=readme-ov-file#using-veaury-in-the-ssr-projects
