### ISSUE TITLE
react-digraph does not compile with TypeScript in VueJS 

### ISSUE THREAD

**Issue by algouser2** [gloriasoft/veaury#50]
Hello, I'm trying to make react-digraph work in VueJS. I was able to set it up with Javascript, but still receiving errors after bringing in Typescript. The purpose of this exercise is to create a prototype which my team can re-use in another VueJS application which is set up with VueCLI.

Here is my repo: https://github.com/algouser2/react-digraph-vuejs
I don't have too much experience with UI development, especially with React, so I've gathered different ideas together from both repos: react-digraph and veaury.
The current errors I'm receiving right now are related to the ReactGraph.tsx file which was basically taken from here and adapted to Typescript: https://github.com/uber/react-digraph/blob/master/src/examples/graph.js
![image](https://user-images.githubusercontent.com/115507904/207823912-158cddf8-f819-45bf-82ab-0b6df5ca4ae6.png)

I'd appreciate if you can provide me with the right direction or a proposed solution

**Comment by devilwjp** [comment]
@algouser2 
This is because the typescript of vue and react conflict.
https://github.com/devilwjp/veaury#typescript-jsx-types-conflict-caused-by-vue-and-react-at-the-same-time

**Comment by devilwjp** [comment]
@algouser2 
You can try issue (#39)

**Comment by devilwjp** [comment]
@algouser2 
This error is at runtime, indicating that the typescript error has been resolved. This runtime error clearly indicates that you passed a VNode into a property that requires ReactNode.

In this case, the parsing method of JSX is generally wrong, and React's JSX parsing should be used instead of Vue's JSX

**Comment by devilwjp** [comment]
@algouser2 
I think it may be that the version of your dependency package is installed incorrectly, and there are two different versions of react, resulting in multiple cases.

![image](https://user-images.githubusercontent.com/38802722/207941450-770910da-fa5e-46a2-8f05-dfa829e6f132.png)

**Comment by devilwjp** [comment]
@algouser2 
The alias configuration of the vue.config.js of this project is completely wrong, delete the part marked in red and it will work normally

![image](https://user-images.githubusercontent.com/38802722/207944832-c363b1f0-bc70-4da1-b3d5-9efc4d5fe25d.png)
