### ISSUE TITLE
How to use in Nextjs

### ISSUE THREAD

**Issue by riderx** [gloriasoft/veaury#72]
i try to understand how to use this in nextjs, do you have some example ?

**Comment by xunfeng911** [comment]
+1

**Comment by devilwjp** [comment]
@riderx @xunfeng911 
Try veaury@^2.5  
https://github.com/gloriasoft/veaury?tab=readme-ov-file#using-veaury-in-the-ssr-projects

**Comment by riderx** [comment]
I have stopped using it
