### ISSUE TITLE
Nuxt 3: Objects are not valid as a React child

### ISSUE THREAD

**Issue by augustjourney** [gloriasoft/veaury#82]
Tried to add react to components to vue app with vite, worked perfectly. Thanks a lot!

Trying to add the same react components to vue in nuxt 3, got errors :(

`Objects are not valid as a React child (found: object with keys {__v_isVNode, __v_skip, type, props, key, ref, scopeId, slotScopeIds, children, component, suspense, ssContent, ssFallback, dirs, transition, el, anchor, target, targetAnchor, staticCount, shapeFlag, patchFlag, dynamicProps, dynamicChildren, appContext, ctx}). If you meant to render a collection of children, use an array instead.`

My deps if that helps

```
"devDependencies": {
    "@nuxt/devtools": "latest",
    "@types/node": "^18",
    "nuxt": "^3.6.1"
  },
  "dependencies": {
    "@vitejs/plugin-react": "^4.0.1",
    "@vitejs/plugin-vue-jsx": "^3.0.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "veaury": "^2.3.12"
  }
```

Maybe you already know where I should dig into. Thanks.

**Comment by devilwjp** [comment]
@augustjourney 
SSR is currently not supported.

**Comment by devilwjp** [comment]
@augustjourney @ekkaiasmith 
Try veaury@^2.5  
https://github.com/gloriasoft/veaury?tab=readme-ov-file#using-veaury-in-the-ssr-projects
